# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('text', models.TextField()),
                ('father', models.PositiveIntegerField(null=True)),
                ('on_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='BoardApp.Board')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
