# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0006_auto_20161014_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
