# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0007_auto_20161015_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostManager',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='father',
            new_name='father_id',
        ),
    ]
